openapi: 3.0.3
info:
  title: Blockchain Interaction API
  version: 1.0.0
  description: A production-ready API for interacting with various blockchain networks.
  termsOfService: https://api.example.com/terms
  contact:
    name: Your Company Name
    url: https://www.example.com/contact
    email: contact@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://wallet.spicefi.xyz/v1
    description: Production Server

components:
  securitySchemes:
      OAuth2:
        type: oauth2
        flows:
          implicit:
            authorizationUrl: https://example.com/oauth/authorize
            scopes:
              read: Read access
              write: Write access

  schemas:
    Transaction:
      type: object
      properties:
        from:
          type: string
          description: The sender's address for the transaction.
        to:
          type: string
          description: The recipient's address for the transaction.
        gas:
          type: integer
          description: The amount of gas units provided for the transaction.
        maxFeePerGas:
          type: integer
          description: The maximum fee per gas unit allowed for the transaction.
        maxPriorityFeePerGas:
          type: integer
          description: The maximum priority fee per gas unit allowed for the transaction.
        gasPrice:
          type: integer
          description: The gas price for the transaction.
        value:
          type: string
          description: The value of the transaction (e.g., token amount).
        data:
          type: string
          description: Additional data associated with the transaction.
        nonce:
          type: integer
          description: The nonce value for the transaction.

    SwapRequest:
      type: object
      properties:
        chainId:
          type: string
          description: The ID of the blockchain chain where the token swap will occur.
        sourceAmount:
          type: string
          description: The amount of tokens to be swapped from the sourceToken.
        sourceToken:
          type: string
          description: The token to be swapped from.
        destinationToken:
          type: string
          description: The token to be received in the swap.
      required:
        - chainId
        - sourceAmount
        - sourceToken
        - destinationToken

    BridgeRequest:
      type: object
      properties:
        sourceChainId:
          type: string
          description: The ID of the source blockchain chain.
        destinationChainId:
          type: string
          description: The ID of the destination blockchain chain.
        sourceToken:
          type: string
          description: The token to be transferred from the source chain to the destination chain.
        destinationToken:
          type: string
          description: The token to be received on the destination chain.
        sourceAmount:
          type: string
          description: The amount of tokens to be transferred.
      required:
        - sourceChainId
        - destinationChainId
        - sourceToken
        - destinationToken
        - sourceAmount

    TransferRequest:
      type: object
      properties:
        token:
          type: string
          description: The token to be transferred.
        amount:
          type: string
          description: The amount of tokens to be transferred.
        recipient:
          type: string
          description: The recipient's address for the token transfer.
      required:
        - token
        - amount
        - recipient


paths:
  /swap:
    post:
      summary: Perform a token swap.
      description: Swaps tokens between two tokens on the same chain.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SwapRequest'
      responses:
        '200':
          description: Response containing transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  transaction:
                    $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /bridge:
    post:
      summary: Bridge tokens between different blockchain networks.
      description: Bridges tokens between different blockchain networks.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BridgeRequest'
      responses:
        '200':
          description: Response containing transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  transaction:
                    $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /transfer:
    post:
      summary: Transfer tokens to another address.
      description: Transfers tokens from one address to another on the same chain.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Response containing transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  transaction:
                    $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

security:
  - OAuth2: []