openapi: 3.0.3
info:
  title: Blockchain Interaction API
  version: 1.0.0
  description: A production-ready API for interacting with various blockchain networks.
  termsOfService: https://api.example.com/terms
  contact:
    name: Your Company Name
    url: https://www.example.com/contact
    email: contact@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://wallet.spicefi.xyz/v1
    description: Production Server

components:
  securitySchemes:
      OAuth2:
        type: oauth2
        flows:
          implicit:
            authorizationUrl: https://example.com/oauth/authorize
            scopes:
              read: Read access
              write: Write access

  schemas:
    Transaction:
      type: object
      properties:
        to:
          type: string
          description: The recipient's address for the transaction.
        gasLimit:
          type: integer
          description: The amount of gas units provided for the transaction.
        maxFeePerGas:
          type: integer
          description: The maximum fee per gas unit allowed for the transaction.
        maxPriorityFeePerGas:
          type: integer
          description: The maximum priority fee per gas unit allowed for the transaction.
        gasPrice:
          type: integer
          description: The gas price for the transaction.
        value:
          type: string
          description: The value of the transaction (e.g., native token amount).
        data:
          type: string
          description: Additional data associated with the transaction (useful when a smart contract is called).

    SwapRequest:
      type: object
      properties:
        accountAddress:
          type: string
          description: The user's account address.
        chainName:
          type: string
          description: The ID of the blockchain where the token swap will occur.
        sourceAmount:
          type: string
          description: The amount of sourceToken to be swapped.
        sourceToken:
          type: string
          description: The token to be swapped from.
        destinationToken:
          type: string
          description: The token to be received in the swap.
      required:
        - accountAddress
        - chainName
        - sourceAmount
        - sourceToken
        - destinationToken

    BridgeRequest:
      type: object
      properties:
        accountAddress:
          type: string
          description: The user's account address.
        sourceChainName:
          type: string
          description: The ID of the source blockchain.
        destinationChainName:
          type: string
          description: The ID of the destination blockchain.
        sourceToken:
          type: string
          description: The token to be transferred from the source chain to the destination chain.
        destinationToken:
          type: string
          description: The token to be received on the destination chain.
        sourceAmount:
          type: string
          description: The amount of tokens to be transferred.
      required:
        - accountAddress
        - sourceChainName
        - destinationChainName
        - sourceToken
        - destinationToken
        - sourceAmount

    YieldRequest:
      type: object
      properties:
        accountAddress:
          type: string
          description: The user's account address.
        chainName:
          type: string
          description: The ID of the blockchain.
        token:
          type: string
          description: The token to be staked.
        amount:
          type: string
          description: The amount of token to be staked.
      required:
        - accountAddress
        - chainName
        - token
        - amount

    TransferRequest:
      type: object
      properties:
        accountAddress:
          type: string
          description: The user's account address.
        token:
          type: string
          description: The token to be transferred.
        amount:
          type: string
          description: The amount of tokens to be transferred.
        recipient:
          type: string
          description: The recipient's address for the token transfer.
        chainName:
          type: string
          description: The ID of the blockchain where the token transfer will occur.
      required:
        - accountAddress
        - token
        - amount
        - recipient
        - chainName

    ProtocolRequest:
      type: object
      properties:
        protocolName:
          type: string
        action:
          type: string
        spender:
          type: string
        receiver:
          type: string
        inputAmount:
          type: string
        inputToken:
          type: string
        outputAmount:
          type: string
        outputToken:
          type: string
        chainName:
          type: string
      required:
        - protocolName
        - action
        - spender
        - chainName


paths:
  /swap:
    post:
      summary: Perform a token swap.
      description: Swaps (buys, sells) source amount of source token for destination token on the same chain.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SwapRequest'
      responses:
        '200':
          description: Response containing transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /bridge:
    post:
      summary: Bridge tokens between different blockchain networks.
      description: Bridges tokens between different blockchain networks by transferring amount of token from source chain to destination chain.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BridgeRequest'
      responses:
        '200':
          description: Response containing transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /yield:
    post:
      summary: Stake in the best yield protocol.
      description: Find highest yield pool and deposit token to the protocol.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/YieldRequest'
      responses:
        '200':
          description: Response containing transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /transfer:
    post:
      summary: Transfer tokens to another address.
      description: Transfers tokens from one address to another on the same chain.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Response containing transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /protocol:
    post:
      summary: Interact with a blockchain protocol.
      description: Performs specific actions on specific apps by depositing or withdrawing an amount of a token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProtocolRequest'
      responses:
        '200':
          description: Response containing transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                    
  /token-balance:
    get:
      summary: Get the user's token balance on a specific chain.
      description: Retrieves the user's balance of a specific token on a given chain.
      parameters:
        - name: accountAddress
          in: query
          description: The user's account address.
          required: true
          schema:
            type: string
        - name: chainName
          in: query
          description: The ID of the blockchain where the token is located.
          required: true
          schema:
            type: string
        - name: tokenName
          in: query
          description: The name of the token whose balance is requested.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response containing the user's token balance.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  balance:
                    type: float
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string


security:
  - OAuth2: []